version: '2.1'
services:
  mysql:
    image: mysql:5.7.19
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: wso2carbon
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 60s
      retries: 5
  identity-server:
    image: wso2is:5.3.0
    ports:
      - "9443:9443"
      - "9763:9763"
    volumes:
        - ./identity-server/carbon/repository/components/lib/mysql-connector-java-5.1.34-bin.jar:/home/wso2carbon/wso2is-5.3.0/repository/components/lib/mysql-connector-java-5.1.34-bin.jar
        - ./identity-server/carbon/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/datasources/master-datasources.xml
    depends_on:
      mysql:
        condition: service_healthy
    links:
        - mysql
